WEWORK_PORTFOLIO = {
    "Northeast": {
        "New York City": {
            "250 Broadway": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "199 Water St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "450 Lexington Ave": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "368 9th Ave": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "8 W 126th St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "430 Park Avenue": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "135 Madison Ave": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "500 7th Ave": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "18 West 18th Street": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "245 5th Ave": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },

        "Boston": {
            "501 Boylston St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "625 Massachusetts Ave": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "One Lincoln Street": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "One Beacon Street": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "One Seaport Square": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "33 Arch St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "200 Portland St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },

        "Washington, DC": {
            "1201 Wilson Boulevard": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "901 North Glebe Road": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "200 Massachusetts Ave NW": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "1701 Rhode Island Ave NW": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "80 M St SE": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Midtown Center": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "700 K Street Northwest": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "1775 Tysons Blvd": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },
    },

    "Southeast": {
        "Atlanta": {
            "120 West Trinity Place": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Coda": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Colony Square": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Terminus": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "1155 Perimeter Center West": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },

        "Charlotte": {
            "615 S College St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "The RailYard South End": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },

        "Nashville": {
            "901 Woodland St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "18th & Chet": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },

        "Tampa": {
            "WeWork Place - 501 E Kennedy Blvd": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },

        "Miami": {
            "Giralda Place": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "2222 Ponce De Leon Blvd": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Brickell City Centre": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Southeast Financial Center": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Wynwood Garage": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },
    },

    "Central": {
        "Chicago": {
            "515 N State": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "222 South Riverside Plaza": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "625 W Adams Street": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "167 North Green Street": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "1 South Dearborn": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "448 North La Salle": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Bridgeview Bank - Uptown": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "330 North Wabash": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },

        "Dallas": {
            "1920 McKinney Ave": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Preston Center": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },
    },

    "West": {
        "Los Angeles": {
            "5161 Lankershim Blvd": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "222 Pacific Coast Hwy": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "520 Broadway": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Campus @ Warner Center": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "The Hubb Long Beach": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "1150 S Olive St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },

        "San Francisco": {
            "Two Embarcadero Center": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "600 California St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "Salesforce Tower": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "201 Spear St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "44 Montgomery": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "650 California St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
            "535 Mission St": {
                "capacity": None,
                "utilization": None,
                "available_capacity": None,
                "demand_growth": None,
                "pipeline": None,
                "operating_margin": None,
                "lease_remaining": None,
            },
        },
    },
}